#服务端口，随便起
server:
  port: 8082
#服务名称
spring:
  application:
    name: order-server
  datasource:
    url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/

#开启驼峰命名及实体映射
mybatis:
  type-aliases-package: org.zxe.order-server.pojo
  configuration:
    map-underscore-to-camel-case: true




